
# generated by: jx gitops variables
export APP_NAME='react-spring'
export BRANCH_NAME='main'
export BUILD_NUMBER='68'
export DOCKERFILE_PATH='Dockerfile'
export DOCKER_REGISTRY='10.97.57.112'
export DOCKER_REGISTRY_ORG='imckify'
export DOMAIN='192.168.49.2.nip.io'
export GIT_BRANCH='main'
export JENKINS_X_URL='http://dashboard-jx.192.168.49.2.nip.io/iMckify/react-spring/main/68'
export JX_CHART_REPOSITORY='docker-registry-jx.192.168.49.2.nip.io'
export JX_REPOSITORY_PASSWORD='admin'
export JX_REPOSITORY_USERNAME='admin'
export KANIKO_FLAGS='--insecure'
export MINK_AS='tekton-bot'
export MINK_IMAGE='10.97.57.112/imckify/react-spring:0.0.74'
export NAMESPACE_SUB_DOMAIN='-jx.'
export PIPELINE_KIND='release'
export PUSH_CONTAINER_REGISTRY='10.97.57.112'
export REPO_NAME='react-spring'
export REPO_OWNER='iMckify'
export VERSION='0.0.74'


# content from git...

# generated by: jx gitops variables
export APP_NAME='react-spring'
export BRANCH_NAME='main'
export DOCKERFILE_PATH='Dockerfile'
export DOCKER_REGISTRY='10.97.57.112'
export DOCKER_REGISTRY_ORG='imckify'
export DOMAIN='192.168.49.2.nip.io'
export GIT_BRANCH='main'
export JX_CHART_REPOSITORY='docker-registry-jx.192.168.49.2.nip.io/charts'
export JX_REPOSITORY_PASSWORD='admin'
export JX_REPOSITORY_USERNAME='admin'
export KANIKO_FLAGS='--insecure'
export MINK_AS='tekton-bot'
export MINK_IMAGE='10.97.57.112/imckify/react-spring:'
export NAMESPACE_SUB_DOMAIN='-jx.'
export PIPELINE_KIND='release'
export PUSH_CONTAINER_REGISTRY='10.97.57.112'
export REPO_NAME='react-spring'
export REPO_OWNER='iMckify'


